### ISSUE TITLE
Character set probleem: encoding tussen bestanden niet consistent

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/MDWS-to-JSON#13]
```
{
    "aet": "boek",
    "code": "12",
    "na": [
        "Histoire abregÃ©e de l'Ã©glise metropolitaine
```

als ik bij `BIBLIO_BOEK_14_39_MAISI_EXP.txt` bij createReadStream niet expliciet `latin1` forceer gaat het goed. Maar er zal wel een reden zijn dat ik dat forceerde... Update: ja er blijken meerdere verschillende encodings gebruikt te worden.

**Comment by companje** [comment]
> 'latin1': Latin-1 stands for ISO-8859-1. This character encoding only supports the Unicode characters from U+0000 to U+00FF. Each character is encoded using a single byte. Characters that do not fit into that range are truncated and will be mapped to characters in that range.

* via `file -b txt/BIBLIO_BOEK_14_39_MAISI_EXP.txt` kun je info over de encoding uitlezen.
* via oa de npm module `detect-character-encoding` kun je in Node encoding herkennen.

Filename | detected by module | confidence | detected by 'file' command
-- | -- | -- | --
1001_185_39_SCANS | ISO-8859-1 | 38 | ASCII
25.KAM-H_290_239_MAISI_AKT | ISO-8859-1 | 28 | ASCII
481-1_290_39_MAISI_EXP | ISO-8859-1 | 32 | ASCII
[UPDATE2 ]463-479_290_39_MAISI_AKT | ISO-8859-1 | 32 | ASCII
[UPDATE2 ]DTB_Archief_ Eemland_72.157b_54_39_MAISI_AKT | ISO-8859-1 | 36 | ASCII
1007-2.7844-tm-7987 | ISO-8859-1 | 30 | ISO-8859
463-2_290_39_MAISI_AKT | ISO-8859-1 | 31 | ISO-8859
481.1-tm-1274 | ISO-8859-1 | 31 | ISO-8859
1001_1_39_MAISI_EXP | ISO-8859-1 | 86 | ISO-8859
34-4.U022a007_54_39_MAISI_EXP | ISO-8859-1 | 49 | ISO-8859
BIBLIO_BOEK_14_39_MAISI_EXP | ISO-8859-1 | 42 | ISO-8859
HUA-beeldbank-12-11-2019 | ISO-8859-1 | 61 | ISO-8859
[FASTUPLOAD ]BEELDBANK_ TEK_PRENT_14_39_MAISI_EXP | ISO-8859-1 | 58 | ISO-8859
337-7_1_39_MAISI_EXP | ISO-8859-1 | 83 | Non-ISO extended-ASCII
0_8_39_MAISI_AO | windows-1252 | 68 | Non-ISO extended-ASCII
BEELDBANK_FOT_DOC_ 3_14_39_MAISI_EXP | windows-1252 | 60 | Non-ISO extended-ASCII
WOGIDS_1_39_MI_WOGIDS | windows-1252 | 76 | Non-ISO extended-ASCII
waterlandsarchief-null_6_131_MAISI_EXP | windows-1252 | 34 | Non-ISO extended-ASCII
1010_1_39_MAISI_EXP2 | windows-1252 | 74 | Non-ISO extended-ASCII

**Comment by companje** [comment]
> 'latin1': Latin-1 stands for ISO-8859-1. This character encoding only supports the Unicode characters from U+0000 to U+00FF. Each character is encoded using a single byte. Characters that do not fit into that range are truncated and will be mapped to characters in that range.

**Comment by companje** [comment]
via `file  -b txt/BIBLIO_BOEK_14_39_MAISI_EXP.txt` kun je info over de encoding uitlezen.
via `iconv -t UTF8 mydata.csv > data-utf8.csv` eventueel omzetten naar een andere encoding.

**Comment by companje** [comment]
Via oa de npm module `detect-character-encoding` kun je in Node encoding herkennen.

file | encoding | confidence
-- | -- | --
1001_185_39_SCANS | ISO-8859-1 | 38

1001_1_39_MAISI_EXP | ISO-8859-1 | 86
1007-2.7844-tm-7987 | ISO-8859-1 | 30
25.KAM-H_290_239_MAISI_AKT | ISO-8859-1 | 28
337-7_1_39_MAISI_EXP | ISO-8859-1 | 83
34-4.U022a007_54_39_MAISI_EXP | ISO-8859-1 | 49
463-2_290_39_MAISI_AKT | ISO-8859-1 | 31
481-1_290_39_MAISI_EXP | ISO-8859-1 | 32
481.1-tm-1274 | ISO-8859-1 | 31
BIBLIO_BOEK_14_39_MAISI_EXP | ISO-8859-1 | 42
HUA-beeldbank-12-11-2019 | ISO-8859-1 | 61
[FASTUPLOAD ]BEELDBANK_TEK_PRENT_14_39_MAISI_EXP | ISO-8859-1 | 58
[UPDATE2 ]463-479_290_39_MAISI_AKT | ISO-8859-1 | 32
[UPDATE2 ]DTB_Archief_Eemland_72.157b_54_39_MAISI_AKT | ISO-8859-1 | 36
0_8_39_MAISI_AO | windows-1252 | 68
1010_1_39_MAISI_EXP2 | windows-1252 | 74
BEELDBANK_FOT_DOC_3_14_39_MAISI_EXP | windows-1252 | 60
WOGIDS_1_39_MI_WOGIDS | windows-1252 | 76
waterlandsarchief-null_6_131_MAISI_EXP | windows-1252 | 34

**Comment by coret** [comment]
Is the character encoding een instelling van het "uitvoer profiel" binnen MAIS Flexis?
Ik had meer UTF-8 verwacht / gehoopt.

**Comment by companje** [comment]
> Is the character encoding een instelling van het "uitvoer profiel" binnen MAIS Flexis?

ja ik geloof het wel.

> Ik had meer UTF-8 verwacht / gehoopt.

ja dat zou wel beter zijn.

Ik zorg iig dat de output van MDWS-to-JSON wel UTF-8 is.

**Comment by companje** [comment]
solved in cebe96730fc58a295aa5966121578f596af81e60
